<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Sign up for our newsletter</name>
   <tag></tag>
   <elementGuidId>52530cb4-b3dc-49b9-a03b-819865e81e0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='account-creation_form']/div/div[7]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.checkbox > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f9e78c83-bc9b-4c34-8b4b-3689970c7607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>newsletter</value>
      <webElementGuid>08f42818-7e22-4308-895f-af5a43cda1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up for our newsletter!</value>
      <webElementGuid>bbdb41ff-99eb-4313-b1dc-4fa6fbdee34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-creation_form&quot;)/div[@class=&quot;account_creation&quot;]/div[@class=&quot;checkbox&quot;]/label[1]</value>
      <webElementGuid>b7cc7a1b-cf87-4c34-92e5-e70725f39590</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account-creation_form']/div/div[7]/label</value>
      <webElementGuid>95481f6c-9c51-44dd-998b-b6d7d64a8fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::label[1]</value>
      <webElementGuid>37aae313-11ec-41fb-b56d-e010deaddd07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receive special offers from our partners!'])[1]/preceding::label[1]</value>
      <webElementGuid>d3e86eda-1e84-41e7-8de2-4f53d9bb909b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your address'])[1]/preceding::label[2]</value>
      <webElementGuid>f11a6ea0-597b-47ba-8fb1-80d116db3956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up for our newsletter!']/parent::*</value>
      <webElementGuid>b367cab7-1557-472d-a197-f9bafbf41508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/label</value>
      <webElementGuid>f2b8c9cf-35e6-4628-b876-7d39949b1bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Sign up for our newsletter!' or . = 'Sign up for our newsletter!')]</value>
      <webElementGuid>ee1b3684-5265-4ed3-a3c3-3f966b513f6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
