<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-12345678910111213141516171819202122_51e29d</name>
   <tag></tag>
   <elementGuidId>b33b99e2-eb9a-461f-bac2-4752d98f32d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='days']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#days</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>edc66dc7-d9ea-4144-9c5c-68c9384760e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>days</value>
      <webElementGuid>81c095b8-4fba-45b7-9038-5677286c2a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>days</value>
      <webElementGuid>0da50def-c60e-4efc-9e9c-b5b8e7734332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>da01d047-f90f-452e-9797-8b393ae01afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													</value>
      <webElementGuid>24776680-6e57-41e3-95e5-fe24c136bde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;days&quot;)</value>
      <webElementGuid>7a6a3a9a-8d58-4b3b-bc64-f352cff989c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='days']</value>
      <webElementGuid>884f7ee2-6f31-4aae-92ca-cf8165f21889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-days']/select</value>
      <webElementGuid>6b70c8b2-4da2-4700-8ae6-7c637bcf3599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::select[1]</value>
      <webElementGuid>93baeb92-0224-47ee-a615-ff6939f8d7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::select[1]</value>
      <webElementGuid>e20e486c-2d71-48a3-9ada-ff5790548911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/preceding::select[1]</value>
      <webElementGuid>1cc34385-9d5b-4dae-80fe-0b17e78c1956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/preceding::select[2]</value>
      <webElementGuid>4aa0a829-9f91-4a99-865b-4e137823e0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f7387b5b-373b-4f0c-8c96-07c5289ec65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'days' and @name = 'days' and (text() = '
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													' or . = '
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													')]</value>
      <webElementGuid>52864128-8173-437b-97c6-387ffb1e8f72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
